### ISSUE TITLE
css class not setting on text input 

### ISSUE THREAD

**Issue by tofuwarrior** [bgcc/sfBootstrapPropelAdminThemePlugin#2]
If I set class="datepicker" on an input widget in the Form configure method it doesn't seem to render the class in the form in the admin generator. Is this a bug? Seems like your theme is just extending the standard Input rendering method but it wasn't clear to me whether this was an issue with the plugin or not.
- great plugin btw, saved me a real headache.

**Comment by 19Gerhard85** [comment]
@tofuwarrior Can you please post a small example of the widget definition e.g.

´´´php
$this->setWidget('date', new ...);
´´´

**Comment by Tschebel** [comment]
i think the problem lies here:
https://github.com/bgcc/sfBootstrapPropelAdminThemePlugin/blob/master/data/generator/sfPropelModule/bootstrap/template/templates/_form_field.php#L27

$attributes comes in this case from the generator.yml and not from the $form->configure() and therefor is most likely empty so $attributes['class'] gets set to "form-control" and the $field->render($attributes) overrides your setting from the form configure method

**Comment by tofuwarrior** [comment]
$this->setWidget('from', new
sfWidgetFormInput(array(),array('class'=>'datetimepicker')));



class doesn't get added, nothing else unusual in the configure method. Can
you replicate this?





On 28 April 2015 at 09:22, 19Gerhard85 <notifications@github.com> wrote:

> @tofuwarrior <https://github.com/tofuwarrior> Can you please post a small
> example of the widget definition e.g.
>
> ´´´php
> $this->setWidget('date', new ...);
> ´´´
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bgcc/sfBootstrapPropelAdminThemePlugin/issues/2#issuecomment-96971223>
> .
>



-- 
Paul Burdon

Projects Director,
Clear Intent
------------------------------------------
paul@clearintent.co.uk
www.clearintent.co.uk
+44(0)2920 140 028

Lao Tzu House,
39 Deri Rd,
Cardiff, CF23 5AH
United Kingdom

**Comment by tofuwarrior** [comment]
Just saw this after posting reply to previous query.

I'm not very familiar with the admin generator config, is this overwriting
the desired behaviour or a bug?

On 28 April 2015 at 12:38, Simon Mitterhofer <notifications@github.com>
wrote:

> i think the problem lies here:
>
> https://github.com/bgcc/sfBootstrapPropelAdminThemePlugin/blob/master/data/generator/sfPropelModule/bootstrap/template/templates/_form_field.php#L27
>
> $attributes comes in this case from the generator.yml and not from the
> $form->configure() and therefor is most likely empty so
> $attributes['class'] gets set to "form-control" and the
> $field->render($attributes) overrides your setting from the form configure
> method
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bgcc/sfBootstrapPropelAdminThemePlugin/issues/2#issuecomment-97028882>
> .
>



-- 
Paul Burdon

Projects Director,
Clear Intent
------------------------------------------
paul@clearintent.co.uk
www.clearintent.co.uk
+44(0)2920 140 028

Lao Tzu House,
39 Deri Rd,
Cardiff, CF23 5AH
United Kingdom

**Comment by 19Gerhard85** [comment]
@tofuwarrior I fixed the issue. You can now add css classes by form which get not overwritten by the generator theme.
