### ISSUE TITLE
fatal error when selecting dataset checkbox in list view

### ISSUE THREAD

**Issue by tofuwarrior** [bgcc/sfBootstrapPropelAdminThemePlugin#3]
When I select a checkbox in the list view in any of my admin list views this error appears:

Fatal error: Call to undefined function format_number_choice() in ......\web\cache\backend\dev\modules\autoInitiative\templates\_chosen_datasets.php on line 3

Looks like it is failing to find the required helper.
Do you know what helper it should load and where? I can put in a pull request.

**Comment by Tschebel** [comment]
format_number_choice is in the I18NHelper

**Comment by tofuwarrior** [comment]
which part of your theme should this be called in.
Sorry for basic questions I'm really unfamiliar with the admin generator
side fo things.
P

On 30 April 2015 at 13:13, Simon Mitterhofer <notifications@github.com>
wrote:

> format_number_choice is in the I18NHelper
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bgcc/sfBootstrapPropelAdminThemePlugin/issues/3#issuecomment-97751795>
> .
>



-- 
Paul Burdon

Projects Director,
Clear Intent
------------------------------------------
paul@clearintent.co.uk
www.clearintent.co.uk
+44(0)2920 140 028

Lao Tzu House,
39 Deri Rd,
Cardiff, CF23 5AH
United Kingdom

**Comment by Tschebel** [comment]
no worries, it's only a line, you don't have to do a pull request,
can you update the file as shown in the commit (clear cache necessary) and see if it works for you

**Comment by tofuwarrior** [comment]
Works fine, didn't know whether it needed including further up.

that call to format_number_choice also occurs here:

web\plugins\sfBootstrapPropelAdminThemePlugin\data\generator\sfPropelModule\bootstrap\template\templates\_list.php

Haven't found a problem so far though.

thanks again.



On 30 April 2015 at 13:34, Simon Mitterhofer <notifications@github.com>
wrote:

> no worries, it's only a line, you don't have to do a pull request,
> can you update the file as shown in the commit (clear cache necessary) and
> see if it works for you
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bgcc/sfBootstrapPropelAdminThemePlugin/issues/3#issuecomment-97755046>
> .
>



-- 
Paul Burdon

Projects Director,
Clear Intent
------------------------------------------
paul@clearintent.co.uk
www.clearintent.co.uk
+44(0)2920 140 028

Lao Tzu House,
39 Deri Rd,
Cardiff, CF23 5AH
United Kingdom
